openapi: 3.2.0
info:
  title: Course Catalog Api V3 Courses API
  description: Exposes some course information by querying CS9 views. Read only API.
  version: '3.0'
  contact:
    name: Student Recruitment
    email: student-recruitment@list.auckland.ac.nz
servers:
- url: httpss://apis.auckland.ac.nz/courses/v3
  description: ''
tags:
- name: Courses API
  description: Courses API
paths:
  /subject/{subject}/courses:
    get:
      tags:
      - Courses API
      description: Search for courses by subject
      operationId: coursesGetBySubject
      parameters:
      - name: subject
        in: path
        description: Subject
        required: true
        schema:
          type: string
          default: COMLAW
          maxLength: 50
          minLength: 0
      - name: from
        in: query
        description: Offset the list of returned results by this amount.
        required: false
        schema:
          type: integer
          format: int32
      - name: size
        in: query
        description: Number of items to retrieve. No default.
        required: false
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: An array of products
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CourseList'
        '400':
          description: Unexpected error
          content:
            '*/*':
              schema:
                type: string
      summary: Courses get by subject
      x-summary-source: derived
  /courses:
    get:
      tags:
      - Courses API
      description: Search for courses
      operationId: coursesGet
      parameters:
      - name: text
        in: query
        description: Search text, eg. students or Spectroscopy
        required: false
        schema:
          type: string
          maxLength: 200
          minLength: 0
      - name: subject
        in: query
        description: Subject
        required: false
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: catalogNbr
        in: query
        description: Catalogue number
        required: false
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: year
        in: query
        description: Course year, e.x. 2014, or empty (current) or 'latestActive
        required: false
        schema:
          type: string
          maxLength: 20
          minLength: 0
      - name: level
        in: query
        description: Level
        required: false
        schema:
          type: integer
          format: int64
      - name: acadGroup
        in: query
        description: Academic Group
        required: false
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: acadOrg
        in: query
        description: Academic Org
        required: false
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: acadCareer
        in: query
        description: Academic Career
        required: false
        schema:
          type: string
          maxLength: 10
          minLength: 0
      - name: mainProgram
        in: query
        description: Main Programme Code
        required: false
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: mainProgramRelated
        in: query
        description: Main Programme Related. Return the courses related to main programme as default.
        required: false
        schema:
          type: boolean
          default: true
      - name: effStatus
        in: query
        description: Effective Status
        required: false
        schema:
          type: string
          maxLength: 1
          minLength: 0
      - name: microcredential
        in: query
        description: Microcredential flag
        required: false
        schema:
          type: boolean
      - name: from
        in: query
        description: Offset the list of returned results by this amount. Default is zero.
        required: false
        schema:
          type: string
          default: '0'
      - name: size
        in: query
        description: Number of items to retrieve. Defaults to 500.
        required: false
        schema:
          type: integer
          format: int32
          default: 500
      responses:
        '200':
          description: An array of courses
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CourseList'
        '400':
          description: Unexpected error
          content:
            '*/*':
              schema:
                type: string
      summary: Courses get
      x-summary-source: derived
  /course/{id}:
    get:
      tags:
      - Courses API
      description: Get course by id
      operationId: courseIdGet
      parameters:
      - name: id
        in: path
        description: Course's unique id, e.g. 001342 or 040230 or 036707
        required: true
        schema:
          type: string
          maxLength: 50
          minLength: 0
      - name: year
        in: query
        description: Course year, e.g. 2003. Use `latestActive` to get the record from last active year. If not specified, defaults to a current year.
        required: false
        schema:
          type: string
          maxLength: 20
          minLength: 0
      responses:
        '200':
          description: Course
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Unexpected error
          content:
            '*/*':
              schema:
                type: string
      summary: Course id get
      x-summary-source: derived
components:
  schemas:
    CourseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Course'
        from:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
        more:
          type: boolean
    Course:
      type: object
      properties:
        id:
          type: string
        year:
          type: integer
          format: int32
        active:
          type: string
        level:
          type: integer
          format: int32
        feeBand:
          type: string
        crseId:
          type: string
        crseOfferNbr:
          type: integer
          format: int32
        effdt:
          type: string
        effdtOffer:
          type: string
        acadCareer:
          type: string
        acadGroup:
          type: string
        acadOrg:
          type: string
        subject:
          type: string
        catalogNbr:
          type: string
        titleLong:
          type: string
        title:
          type: string
        description:
          type: string
        text:
          type: array
          items:
            type: string
        catalogPrint:
          type: string
        componentPrimary:
          type: string
        gradingBasis:
          type: string
        rqrmntGroup:
          type: string
        rqrmntDescr:
          type: string
        splitOwner:
          type: string
        unitsAcadProg:
          type: number
          format: double
        ssrComponent:
          type: string
        mainProgram:
          type: string
        effStatus:
          type: string
        microcredential:
          type: boolean
  securitySchemes:
    apikey:
      type: apiKey
x-headmatter:
  readable_by: []
